### ISSUE TITLE
Missing Encounter for Edge of the Earth Campaign 

### ISSUE THREAD

**Issue by rautesamtr** [neizerth/ArkhamDivider#12]
Hi,
i just got my Edge of the Earth Campaign and prepared the dividers for it.
While sorting the cards i noticed the "Memorials of the Lost" is missing in the generation (there is also no icon available for it).

https://arkhamdb.com/find?q=m:memorials_of_the_lost&sort=set&view=list&decks=encounter

**Comment by neizerth** [comment]
Fixed! Thank you!
